language: python
python:
  - "2.6"
  - "2.7"
before_script:
  - flake8 basket
script: coverage run setup.py test
install:
  - pip install -r requirements/dev.txt --use-mirrors
after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls --use-mirrors
  - coveralls
notifications:
  irc:
    channels:
      - "irc.mozilla.org#basket"
    on_success: change
    on_failure: always
    use_notice: true
